### ISSUE TITLE
Windows Install Package Problems

### ISSUE THREAD

**Issue by GeeH** [PHPEmbark/packages#1]
HP Pavillion Laptop running Windows 8.1 nearly new so little/no custom software installed.
1. Took ages to unpack and copy the 8k+ files - is this correct?
2. No idea what I was supposed to do once I'l unpacked the release, so I just run `run.bat`
3. Once I realised what was happening, everything seemed to work well; visiting 127.0.0.1:8080 gave me a Not Found resource which looked right, and I saw the request in the run.bat window.

NICE JOB!

> Sorry if these are stupid points or not relevant, just a brain dump - feel free to ignore. Basically this is an issue to say all was well!

**Comment by auroraeosrose** [comment]
Heh

Yeah that package also has two application "installed" which is why it's so big
I'd like to provide just installers as well - so you think we need a "readme" or something there too?

Also did you try running the sqlite gui or the text editor?

**Comment by GeeH** [comment]
I think my main problem is I have no idea what this package is or what it does! I can knock up some documentation after testing if you let me know here in small words what it does.

G

**Comment by auroraeosrose** [comment]
Hmm - first of all check the setup presentation in the phpembark
second - it provides
1. local installs of the gui and text editor tools that are "default" for doing phpembark
2. php with the right ini settings and right extensions for doing phpembark - and a run script so that you don't have to touch the command line to make the server run

so it's a complete install of a tool to talk to the db, a tool to write code, and a php test server ready to run, no setup or installation necessary

**Comment by dcousineau** [comment]
FYI we have an Asus Windows 8.1 tester machine that's pretty underspecced but barebones I can test iterations of this on if you ping me to do so

**Comment by auroraeosrose** [comment]
I'm debating whether to only provide installers for the tools instead of the pre-installed versions - as you said they're pretty big  - we'll also want to (when it's ready) have a ready to go document root set up with example files and such :)  this is only round 1

@dcousineau  feel free to test, it's alpha but it appears to work great (windows is actually the easiest of the setups to do)

**Comment by GeeH** [comment]
Apologies, I'm guilty of not reading the presentation, will do it tomorrow
and comment again!

**Comment by auroraeosrose** [comment]
Heh - it's not finished for other sections yet - feel free to add whatever

**Comment by auroraeosrose** [comment]
Ping @dcousineau and @GeeH - this is ready for an initial release - the release package now includes only installers for the large software, run script helpers, and a setup.pdf file which should help :)
